2018-09-17 16:07:33 - classification.scripts.network - INFO - Building Model...
2018-09-17 16:07:57 - __main__ - ERROR - get_pred_confidence_df() missing 1 required positional argument: 'params'
Traceback (most recent call last):
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 60, in <module>
    SignFacingPredictor(predict_config).predict()
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 41, in predict
    self._save_results(pred_df)
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 29, in _save_results
    pred_df = postprocess.get_pred_confidence_df(pred_df)
TypeError: get_pred_confidence_df() missing 1 required positional argument: 'params'
2018-09-17 16:10:22 - classification.scripts.network - INFO - Building Model...
2018-09-17 16:10:52 - __main__ - INFO - saving predicted results...
2018-09-17 16:10:52 - __main__ - ERROR - [Errno 2] No such file or directory: './ftp_bundle/model_best_thresholds.json'
Traceback (most recent call last):
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 60, in <module>
    SignFacingPredictor(predict_config).predict()
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 41, in predict
    self._save_results(pred_df)
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 33, in _save_results
    lt, rt = postprocess.load_best_thresholds_json(self.BEST_THREHSHOLDS_PATH)
  File "/home/mihaic/dev/imagerecognition/python_modules/classification/scripts/signs_facing_classifier/postprocess.py", line 98, in load_best_thresholds_json
    best_thresholds = io_utils.json_load(path)
  File "/home/mihaic/dev/imagerecognition/python_modules/apollo_python_common/io_utils.py", line 50, in json_load
    with open(json_path) as json_data_file:
FileNotFoundError: [Errno 2] No such file or directory: './ftp_bundle/model_best_thresholds.json'
2018-09-17 16:19:33 - classification.scripts.network - INFO - Building Model...
2018-09-17 16:20:02 - __main__ - INFO - saving predicted results /home/mihaic/dev/imagerecognition/python_modules/classification/dev/sign_facing/predict...
2018-09-17 16:20:02 - __main__ - ERROR - [Errno 2] No such file or directory: './ftp_bundle/model_best_thresholds.json'
Traceback (most recent call last):
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 61, in <module>
    SignFacingPredictor(predict_config).predict()
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 42, in predict
    self._save_results(pred_df)
  File "../../../../classification/run/signs_facing_classifier/sf_predictor.py", line 33, in _save_results
    lt, rt = postprocess.load_best_thresholds_json(self.BEST_THREHSHOLDS_PATH)
  File "/home/mihaic/dev/imagerecognition/python_modules/classification/scripts/signs_facing_classifier/postprocess.py", line 98, in load_best_thresholds_json
    best_thresholds = io_utils.json_load(path)
  File "/home/mihaic/dev/imagerecognition/python_modules/apollo_python_common/io_utils.py", line 50, in json_load
    with open(json_path) as json_data_file:
FileNotFoundError: [Errno 2] No such file or directory: './ftp_bundle/model_best_thresholds.json'
2018-09-17 16:45:22 - classification.scripts.network - INFO - Building Model...
2018-09-17 16:45:51 - __main__ - INFO - saving predicted results /home/mihaic/dev/imagerecognition/python_modules/classification/dev/sign_facing/predict...
2018-09-17 16:45:51 - __main__ - INFO - applying best thresholds - lt: 0.5299999999999998, rt: 0.1
2018-09-17 16:51:52 - classification.scripts.network - INFO - Building Model...
2018-09-17 16:52:16 - __main__ - INFO - saving predicted results /home/mihaic/dev/imagerecognition/python_modules/classification/dev/sign_facing/predict...
2018-09-17 16:52:16 - __main__ - INFO - applying best thresholds - lt: 0.5299999999999998, rt: 0.1
